# Generated by Django 4.2.23 on 2025-08-27 23:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inmueble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('m2_construido', models.FloatField(default=0)),
                ('m2_total', models.FloatField(default=0)),
                ('estacionamientos', models.PositiveSmallIntegerField(default=0)),
                ('habitaciones', models.PositiveSmallIntegerField(default=0)),
                ('baños', models.PositiveSmallIntegerField(default=0)),
                ('direccion', models.CharField(max_length=100)),
                ('arriendo_mensual', models.DecimalField(decimal_places=2, max_digits=8)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('tipo_inmueble', models.CharField(choices=[('CASA', 'Casa'), ('DPTO', 'Departamento'), ('PARC', 'Parcela')], max_length=20)),
                ('comuna', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inmuebles', to='portal.comuna')),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inmuebles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
