# Generated by Django 4.2.23 on 2025-09-02 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_inmueble_imagen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inmueble',
            old_name='baños',
            new_name='banos',
        ),
    ]
