# Generated by Django 4.2.23 on 2025-09-02 14:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_rename_baños_inmueble_banos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmueble',
            name='propietario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inmuebles', to=settings.AUTH_USER_MODEL),
        ),
    ]
