# Generated by Django 4.2.23 on 2025-09-02 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_alter_inmueble_propietario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmueble',
            name='arriendo_mensual',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
