# Generated by Django 4.2.23 on 2025-09-02 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_alter_solicitudarriendo_arrendatario'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudarriendo',
            name='mensaje',
            field=models.TextField(blank=True, null=True),
        ),
    ]
