# Generated by Django 4.2.23 on 2025-09-02 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_solicitudarriendo_mensaje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmueble',
            name='tipo_inmueble',
            field=models.CharField(choices=[('Casa', 'Casa'), ('Departamento', 'Departamento'), ('Parcela', 'Parcela')], max_length=20),
        ),
        migrations.AlterField(
            model_name='solicitudarriendo',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aceptado', 'Aceptada'), ('Rechazado', 'Rechazada')], default='Pendiente', max_length=10),
        ),
    ]
