# Generated by Django 4.2.23 on 2025-09-02 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_alter_inmueble_tipo_inmueble_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmueble',
            name='imagen',
            field=models.ImageField(default='sin_imagen', upload_to='inmuebles/'),
        ),
    ]
