# Generated by Django 4.2.23 on 2025-09-02 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_alter_inmueble_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfiluser',
            name='imagen',
            field=models.ImageField(default='perfil-default.png', upload_to='foto_perfil'),
        ),
    ]
