# Generated by Django 4.2.23 on 2025-09-03 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0010_perfiluser_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfiluser',
            name='imagen',
            field=models.ImageField(default='perfil-default.png', upload_to='fotos_perfil'),
        ),
    ]
