# Generated by Django 4.2.23 on 2025-09-03 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0011_alter_perfiluser_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfiluser',
            name='imagen',
            field=models.ImageField(default='sin_imagen', upload_to='fotos_perfil/'),
        ),
    ]
