# Generated by Django 4.2.23 on 2025-09-08 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0012_alter_perfiluser_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmueble',
            name='imagen',
            field=models.ImageField(default='inmuebles/sin_imagen.jpg', upload_to='inmuebles/'),
        ),
    ]
